### ISSUE TITLE
Wrong link to workspace steps

### ISSUE THREAD

**Issue by GibzonDev** [aws-samples/aws-serverless-application-catalog-workshop#2]
On this page: https://application-catalog.serverlessworkshops.io/020_prerequisites/
The link to creating the workspace is wrong. It points to:
https://application-catalog.serverlessworkshops.io/020_prerequisites/workspace
When it should be:
https://application-catalog.serverlessworkshops.io/020_prerequisites/workspace/workspace/

**Comment by enr1c091** [comment]
Thanks for letting me know! Already fixed the link ref.
